services:
  - type: web
    name: laundryy
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Laundry_p.wsgi"
    migrateCommand: |
      python manage.py migrate
      python create_admin.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://laundry_s6aq_user:QAq4MNwi4Er8oDGkBtncjhJe2ddfRT1E@dpg-d0vk71p5pdvs738jvhsg-a/laundry_s6aq
staticPublishPath: staticfiles
